from pydantic import BaseModel, Field
from typing import List, Optional

class CompetitorDetails(BaseModel):
    name: str = Field(..., description="Name of the competitor.")
    market_share_percentage: float = Field(..., description="Estimated market share percentage.")
    key_strengths: List[str] = Field(..., description="Strengths of the competitor.")
    vulnerabilities: List[str] = Field(..., description="Vulnerabilities we can capitalize on.")

class TargetAudiencePersona(BaseModel):
    segment_name: str = Field(..., description="Target segment name.")
    pain_points: List[str] = Field(..., description="Key frustrations experienced by this persona.")
    willingness_to_pay_rating: int = Field(..., description="Rating from 1-10 on willingness to pay.")

class MarketAnalysisReport(BaseModel):
    """
    Highly detailed structured analysis report generated by the Market Analyst.
    """
    market_size_description: str = Field(..., description="Description of the TAM/SAM/SOM opportunity.")
    personas: List[TargetAudiencePersona] = Field(..., description="Target audience segments.")
    competitor_landscape: List[CompetitorDetails] = Field(..., description="List of competitors.")
    industry_drivers: List[str] = Field(..., description="Key drivers (technological, economic, social).")
    overall_viability_score: int = Field(..., description="Score 1-10 rating viability.")
    suggested_value_proposition: str = Field(..., description="Core value prop recommendation.")

class CriticFeedback(BaseModel):
    """
    Structured feedback evaluation provided by Department Critic nodes.
    """
    is_approved: bool = Field(..., description="True if report passes quality bar, False otherwise.")
    feedback: str = Field(..., description="Detailed constructive feedback or approval summary.")
    score: int = Field(..., description="Quality score from 1-10.")
