from pydantic import BaseModel, Field
from typing import List

class SystemArchitecture(BaseModel):
    """
    High-level technology stack and architectural patterns selected by the System Architect.
    """
    frontend_tech: str = Field(description="Frontend technologies (e.g. Next.js, Flutter).")
    backend_tech: str = Field(description="Backend stack and framework (e.g. Python FastAPI, Node.js).")
    database_choice: str = Field(description="Primary database choice and reasoning.")
    architecture_pattern: str = Field(description="Core system pattern (e.g. Microservices, Event-Driven, MVC).")
    architectural_rationale: str = Field(description="Why this stack is appropriate for the target market segment.")

class APIEndpoint(BaseModel):
    method: str = Field(description="HTTP Request method (e.g. GET, POST).")
    path: str = Field(description="URI endpoint path.")
    description: str = Field(description="Short description of the endpoint function.")

class TechnicalBlueprint(BaseModel):
    """
    Detailed blueprint/PRD generated by the Technical Planner.
    """
    database_schema_concept: str = Field(description="Textual or schema description of database models.")
    core_api_endpoints: List[APIEndpoint] = Field(description="Necessary API endpoints for building the MVP.")
    infrastructure_and_deployment: str = Field(description="Details on cloud provider, dockerization, and hosting.")
    mvp_roadmap_phases: List[str] = Field(description="List of execution phases.")
